apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: routeoption
spec:
  options:
    timeout: 180s
    rateLimitConfigs:
      refs:
      - name: rate-limit-config
        namespace: default
---
apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: rate-limit-config
spec:
  raw:
    descriptors:
      - key: generic_key
        value: counter
        rateLimit:
          requestsPerUnit: 1
          unit: HOUR
    rateLimits:
    - actions:
      - genericKey:
          descriptorValue: counter
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ollama
spec:
  parentRefs:
  - kind: Service
    group: ""
    name: ollama
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.solo.io
            kind: RouteOption
            name: routeoption
      backendRefs:
        - name: ollama
          port: 80