apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag
---
apiVersion: v1
kind: Service
metadata:
  name: rag
spec:
  selector:
    app: rag
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rag-stable
spec:
  selector:
    app: rag
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rag-canary
spec:
  selector:
    app: rag
  ports:
  - port: 80
    targetPort: 8000
