apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: default
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: docker.io/linsun/demo:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 8001
        env:
          - name: OLLAMA_BASE_URL
            value: "http://host.docker.internal:11434"
            # value: "http://ollama:80"
  strategy:
    canary:
      canaryService: rollouts-demo-canary # our created canary service
      stableService: rollouts-demo-stable # our created stable service
      trafficRouting:
        managedRoutes:
        - name: "canary-header"
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: rollouts-demo-http-route
            namespace: default
      steps:
      - setWeight: 30
      - setHeaderRoute:
          name: "canary-header"
          match:
            - headerName: x-rollout-canary
              headerValue:
                exact: "true" 
      - pause: {}
      - setWeight: 60
      - pause: {duration: 30s}
      - setWeight: 100
      - pause: {duration: 30s}
